### ISSUE TITLE
JavaScript 세션에서 개체 선택시 상세보기 구현

### ISSUE THREAD

**Issue by DaeguShiba** [koreaXCO/Style-Website-DemoVersion#2]
개체 상세보기에 자바스크립트 관련내용 구현예정 기능 추가 필요

**Comment by DaeguShiba** [comment]
jquery를 이용한 문제 해결완료

**Comment by DaeguShiba** [comment]
각 개체의 기본 실용 실무 관련 코드 추가 및 설명 필요

**Comment by codingBlueOcean** [comment]
java script 하이퍼링크에 마우스 올렸을때 다른 색으로 변하게 해서 하이퍼링크임을 나타내게 하는 기능 추가 바람.

**Comment by DaeguShiba** [comment]
이슈 종료
