### ISSUE TITLE
CSS article에서 각 개체에 기능추가

### ISSUE THREAD

**Issue by DaeguShiba** [koreaXCO/Style-Website-DemoVersion#4]
1.각 개체의 이미지에 마우스 올려두면 CSS 애니메이션 구동
2.돋보기 이모지 클릭시 --> CSS 상세코드 보여주기

**Comment by codingBlueOcean** [comment]
1. 의 경우 마우스를 올려두면 CSS구동하도록 할 시 드래그 전에 화면에 이미지가 보이지 않음. 그래서 마우스 드래그 없이도 계속 애니메이션이 움직이는 코드 그대로 놔둠.

**Comment by DaeguShiba** [comment]
CSS article에서 돋보기 버튼 클릭시 DB환경에서 불러오기
node.js MySql사용하여 데이터베이스 구축및 웹사이트에 불러오기 필요

**Comment by codingBlueOcean** [comment]
2. 돋보기 아이콘 클릭시 CSS코드를 팝업창에 나타나게 함. 
 -> 하지만, 팝업창 디자인 수정이 필요.

**Comment by codingBlueOcean** [comment]
팝업창 디자인 간략화
